### ISSUE TITLE
Fortuna install google colab

### ISSUE THREAD

**Issue by nilsleh** [awslabs/fortuna#7]
I want to explore fortuna with some experiments in a google colab notebook, but having trouble with the install. [Here](https://colab.research.google.com/drive/1zK4uXLPGOkNWqRuqFszR9opg2bnFzDb1?usp=sharing) is a notebook just trying to install fortuna and use the `CalibRegressor`.

`AttributeError: module 'numpy' has no attribute '_no_nep50_warning'`

**Comment by gianlucadetommaso** [comment]
Hi Nils,
thanks for this! The problem seems to be that Colab ignored the version restrictions specified in [pyproject.toml](https://github.com/awslabs/fortuna/blob/main/pyproject.toml). If after `%pip install fortuna` you add another cell with the command `%pip install flax==0.6.2`, then everything seems to work fine.

I'll try to figure out why this is happening asap, but perhaps for now you could try this quick fix? Thanks!

**Comment by nilsleh** [comment]
Thank you for your quick reply, that does solve the issue!

**Comment by gianlucadetommaso** [comment]
Closing this. Please reach out again if any other problem pops up!
